### ISSUE TITLE
Post (Call for DMV Website Standards)

### ISSUE THREAD

**Issue by lukefretwell** [civicdmv/ops#19]
## Checklist

- [x] Create a doc, add link in 'Doc' section below (add comment permissions)
- [x] When ready for ready, add @lukefretwell to the issue
- [x] When editorial review is finalized, add to Medium, customize and submit for review
- [x] Once published, promote to social channels

## Messages

* We're creating a DMV Website Standards project
* Here are the MVP criteria
* Link to GitHub issue https://github.com/civicdmv/ops/issues/2
* Link to spreadsheet
* Want feedback
* Tell how to comment (doc + issue)

## Doc

[https://docs.google.com/document/d/1kg1n5EfU1iQ4_BjepX33rdmT3e3vw60cjZGl2ltagHQ/edit#](#)

**Comment by rkroft** [comment]
@lukefretwell ready for you to check it out
